### ISSUE TITLE
Run Lighthouse Audit

### ISSUE THREAD

**Issue by StegSchreck** [StegSchreck/uberpage#7]
* run lighthouse audit in Google Chrome dev console
* prioritize findings

**Comment by StegSchreck** [comment]
[2020-04-26_AngularCV_lighthouse_audit_results.pdf](https://github.com/StegSchreck/uberpage/files/4535158/Untitled.Document.pdf)

**Comment by blueocto** [comment]
Here is a PDF report if it helps :-)
[Google Lighthouse Report.pdf](https://github.com/StegSchreck/uberpage/files/5434759/Untitled.Document.pdf))
